// DE188-RU-30/7.5-3 Bare glass LCD panel
// byte array[F E G D A C B P]
// byte array[BP0 BP1 BP2 BP3 BP0 BP1 BP2 BP3]
#define BLANK 0b00000000
#define SEGA  0b00001000
#define SEGB  0b00000010
#define SEGC  0b00000100
#define SEGD  0b00010000
#define SEGE  0b01000000
#define SEGF  0b10000000
#define SEGG  0b00100000
#define SEGP  0b00000001 // Symbol

#define SPACE   (BLANK)
#define QUMARK  (SEGB|SEGF)
#define PERC    (SEGB|SEGE|SEGG)
#define APH     (SEGG)
#define OBRAC   (SEGA|SEGD|SEGE|SEGF)
#define CBRAC   (SEGA|SEGB|SEGC|SEGD)
#define MINUS   (SEGG)
#define DOT     (SEGP)
#define NUM0    (SEGA|SEGB|SEGC|SEGD|SEGE|SEGF)
#define NUM1    (SEGB|SEGC)
#define NUM2    (SEGA|SEGB|SEGD|SEGE|SEGG)
#define NUM3    (SEGA|SEGB|SEGC|SEGD|SEGG)
#define NUM4    (SEGB|SEGC|SEGF|SEGG)
#define NUM5    (SEGA|SEGC|SEGD|SEGF|SEGG)
#define NUM6    (SEGA|SEGC|SEGD|SEGE|SEGF|SEGG)
#define NUM7    (SEGA|SEGB|SEGC)
#define NUM8    (SEGA|SEGB|SEGC|SEGD|SEGE|SEGF|SEGG)
#define NUM9    (SEGA|SEGB|SEGC|SEGD|SEGF|SEGG)

#define LETA    (SEGA|SEGB|SEGC|SEGE|SEGF|SEGG)
#define LETB    (SEGC|SEGD|SEGE|SEGF|SEGG)
#define LETC    (SEGA|SEGD|SEGE|SEGF)
#define LETD    (SEGB|SEGC|SEGD|SEGE|SEGG)
#define LETE    (SEGA|SEGD|SEGE|SEGF|SEGG)
#define LETF    (SEGA|SEGE|SEGF|SEGG)
#define LETG    (SEGA|SEGC|SEGD|SEGE|SEGF|SEGG)
#define LETH    (SEGB|SEGC|SEGE|SEGF|SEGG)
#define LETI    (SEGB|SEGC)
#define LETJ    (SEGB|SEGC|SEGD|SEGC)
#define LETK    (SEGB|SEGC|SEGE|SEGF|SEGG)
#define LETL    (SEGD|SEGE|SEGF)
#define LETM    (SEGA|SEGB|SEGC|SEGE|SEGF)
#define LETN    (SEGC|SEGE|SEGG)
#define LETO    (SEGA|SEGB|SEGC|SEGD|SEGE|SEGF)
#define LETP    (SEGA|SEGB|SEGE|SEGF|SEGG)
#define LETQ    (SEGA|SEGB|SEGC|SEGD|SEGE|SEGF|SEGG)
#define LETR    (SEGE|SEGG)
